### ISSUE TITLE
Google Open ID Deprecated

### ISSUE THREAD

**Issue by mifantrax** [piersharding/moodle-google#11]
Trying to register a moodle instance i got to face the error message that i cannot add a new instance.

are there any plans to move to Oauth2 or Google+ Signin ?

https://developers.google.com/accounts/docs/OpenID2

Thanks

**Comment by piersharding** [comment]
Hi - I haven't been following these developments.  At the moment I don't have any plans to do the necessary work.

Cheers.

**Comment by vlashdn** [comment]
This has now been updated.
