### ISSUE TITLE
Can this be updated for OpenID Connect?

### ISSUE THREAD

**Issue by vlashdn** [piersharding/moodle-google#12]
With Google dropping OpenID 2.0 as of yesterday, Apr 20/2015, one of the best Google/Moodle integration tools is about to become broken. Is there anyone still working on this?

**Comment by piersharding** [comment]
Hi - I would, but I just don't have the time for it at the moment.  I may get some time in a month or two (I know this doesn't help).  It would help if someone else spent the time researching the most light weight viable PHP OpenID Connect library...

**Comment by vlashdn** [comment]
Something like https://github.com/jumbojett/OpenID-Connect-PHP ?

**Comment by piersharding** [comment]
OK - thanks - I'll have a look.

**Comment by vlashdn** [comment]
Research, I'm good at. If you need me to look deeper, I will.

**Comment by piersharding** [comment]
Thanks for your help.  I have it working for Google Apps, so I see what I can do over the next few days for auth/gauth.

**Comment by piersharding** [comment]
I've pushed up a first version working with OpenID Connect - please test and let me know how you get on.

**Comment by vlashdn** [comment]
Worked perfectly. You are awesome!
