### ISSUE TITLE
Open-ID errors.

### ISSUE THREAD

**Issue by vlashdn** [piersharding/moodle-google#13]
Noticed it first with new users. Cleared my old approved APIs to create the same error. Just installed the newest update and the error has changed. 

Exception - Unable to verify signature

More information about this error

Debug info: 
Error code: generalexceptionmessage
Stack trace:
line 202 of /auth/gauth/lib/OpenIDConnectClient.php5: OpenIDConnectClientException thrown
line 78 of /auth/gauth/index.php: call to OpenIDConnectClient->authenticate()

**Comment by piersharding** [comment]
Hi - this at the very least is sloppy error handling.  I've pushed up some better catching.

**Comment by vlashdn** [comment]
Maybe I have the API set wrong? 

error/OpenId negotiation with Google failed

More information about this error

Debug info: 
Error code: OpenId negotiation with Google failed
$a contents:
Stack trace:
line 463 of /lib/setuplib.php: moodle_exception thrown
line 128 of /auth/gauth/index.php: call to print_error()

**Comment by piersharding** [comment]
something strange is going on with the provider URL - I've changed it again, and pushed.  Changed from accounts.google.com to https://accounts.google.com.

**Comment by vlashdn** [comment]
That fixed it Piers.
