### ISSUE TITLE
OpenID Connect failure

### ISSUE THREAD

**Issue by vlashdn** [piersharding/moodle-google#14]
This one is weird. Between 9am and 3PM PDT, everything works. Then, like clockwork:

error/OpenId negotiation with Google failed

More information about this error

Debug info: 
Error code: OpenId negotiation with Google failed
$a contents:
Stack trace:
line 463 of /lib/setuplib.php: moodle_exception thrown
line 128 of /auth/gauth/index.php: call to print_error()

Not sure if this is the client or Google.

**Comment by piersharding** [comment]
Hi - can you enable developer debug and see what you get in the apache error log?

**Comment by vlashdn** [comment]
That was with developer debug on.

Here is part of the error log:

[Tue Apr 28 15:43:47 2015] [error] [client 50.65.39.75] Default exception handler: error/OpenId negotiation with Google failed Debug: \\nError code: OpenId negotiation with Google failed\\n$a contents: \\n* line 463 of /lib/setuplib.php: moodle_exception thrown\\n* line 128 of /auth/gauth/index.php: call to print_error()\\n, referer: https://accounts.google.com/AccountChooser?service=lso&continue=https%3A%2F%2Faccounts.google.com%2Fo%2Foauth2%2Fv2%2Fauth%3Fscope%3Dopenid%2Bemail%2Bprofile%26response_type%3Dcode%26nonce%3Dd113bc8069d19ad25bb703b35442cbe2%26redirect_uri%3Dhttps%3A%2F%2Fcourses.learn60.ca%2Fauth%2Fgauth%2F%26state%3D1ee3ae854bb23772c00098653ca0c866%26client_id%3D610738832024-7toflgr5iacjn85rjqer84u7se58apto.apps.googleusercontent.com%26hl%3Den%26from_login%3D1%26as%3D1c82aab3f02aab3f&btmpl=authsub&hl=en
[Tue Apr 28 15:43:47 2015] [error] [client 50.65.39.75] PHP Notice:  get_context_instance() is deprecated, please use context_xxxx::instance() instead.<ul style="text-align: left" data-rel="backtrace"><li>line 4024 of /lib/deprecatedlib.php: call to debugging()</li><li>line 58 of /blocks/quickcourselist/block_quickcourselist.php: call to get_context_instance()</li><li>line 296 of /blocks/moodleblock.class.php: call to block_quickcourselist->get_content()</li><li>line 238 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()</li><li>line 993 of /lib/blocklib.php: call to block_base->get_content_for_output()</li><li>line 1045 of /lib/blocklib.php: call to block_manager->create_block_contents()</li><li>line 353 of /lib/blocklib.php: call to block_manager->ensure_content_created()</li><li>line 6 of /theme/sky_high/layout/general.php: call to block_manager->region_has_content()</li><li>line 870 of /lib/outputrenderers.php: call to include()</li><li>line 800 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()</li><li>line 2568 of /lib/output in /Library/Server/Web/moodle/lib/weblib.php on line 2948, referer: https://accounts.google.com/AccountChooser?service=lso&continue=https%3A%2F%2Faccounts.google.com%2Fo%2Foauth2%2Fv2%2Fauth%3Fscope%3Dopenid%2Bemail%2Bprofile%26response_type%3Dcode%26nonce%3Dd113bc8069d19ad25bb703b35442cbe2%26redirect_uri%3Dhttps%3A%2F%2Fcourses.learn60.ca%2Fauth%2Fgauth%2F%26state%3D1ee3ae854bb23772c00098653ca0c866%26client_id%3D610738832024-7toflgr5iacjn85rjqer84u7se58apto.apps.googleusercontent.com%26hl%3Den%26from_login%3D1%26as%3D1c82aab3f02aab3f&btmpl=authsub&hl=en

**Comment by vlashdn** [comment]
[Tue Apr 28 15:47:28 2015] [error] [client 50.65.39.75] auth/gauth: auth/gauth: failure: Unable to verify signature, referer: https://accounts.google.com/AccountChooser?service=lso&continue=https%3A%2F%2Faccounts.google.com%2Fo%2Foauth2%2Fv2%2Fauth%3Fscope%3Dopenid%2Bemail%2Bprofile%26response_type%3Dcode%26nonce%3D127507d4ee8c76d7a184bb92b650f886%26redirect_uri%3Dhttps%3A%2F%2Fcourses.learn60.ca%2Fauth%2Fgauth%2F%26state%3D9b22372a160c062b555d22c8b1a9d7c2%26client_id%3D610738832024-7toflgr5iacjn85rjqer84u7se58apto.apps.googleusercontent.com%26hl%3Den%26from_login%3D1%26as%3Da4f3ad41f5bff11&btmpl=authsub&hl=en
[Tue Apr 28 15:47:28 2015] [error] [client 50.65.39.75] Default exception handler: error/OpenId negotiation with Google failed Debug: \\nError code: OpenId negotiation with Google failed\\n$a contents: \\n* line 463 of /lib/setuplib.php: moodle_exception thrown\\n* line 128 of /auth/gauth/index.php: call to print_error()\\n, referer: https://accounts.google.com/AccountChooser?service=lso&continue=https%3A%2F%2Faccounts.google.com%2Fo%2Foauth2%2Fv2%2Fauth%3Fscope%3Dopenid%2Bemail%2Bprofile%26response_type%3Dcode%26nonce%3D127507d4ee8c76d7a184bb92b650f886%26redirect_uri%3Dhttps%3A%2F%2Fcourses.learn60.ca%2Fauth%2Fgauth%2F%26state%3D9b22372a160c062b555d22c8b1a9d7c2%26client_id%3D610738832024-7toflgr5iacjn85rjqer84u7se58apto.apps.googleusercontent.com%26hl%3Den%26from_login%3D1%26as%3Da4f3ad41f5bff11&btmpl=authsub&hl=en

**Comment by piersharding** [comment]
Hi - I've pushed up some debug and some changes from the OpenIDConnect library - I just this minute saw an intermittent problem similar to above, but repeated the login successfully.  Not sure if it's a service issue or some weird side effect of how the library supports the protocol.

Please send me the debug.

Thanks,
Piers.

**Comment by vlashdn** [comment]
error/OpenId negotiation with Google failed

More information about this error

Debug info: 
Error code: OpenId negotiation with Google failed
$a contents:
Stack trace:
line 463 of /lib/setuplib.php: moodle_exception thrown
line 128 of /auth/gauth/index.php: call to print_error()

Same info, sorry.

**Comment by vlashdn** [comment]
And now I can't get it to fail.

**Comment by piersharding** [comment]
As best I can tell, the failure was happening in verifyJWTsignature() - I can't get it to repeat either.  It's possible that Google was having some issues with a zone at that time (unlikely but possible), but without being able to recreate it, I can't do any further investigation I think.

**Comment by vlashdn** [comment]
I'll be monitoring it tonight to see if it fails again.




Craig.



—
Craig Simmons,Network Consultant

Northern BC Distance Education School

http://nbcdes.com

(250)261-5665

**Comment by vlashdn** [comment]
So far, it has not failed and I have not had any more reports of it failing. Will continue to monitor for another 24 hours, then we can assume it was Google and close this.

**Comment by vlashdn** [comment]
Was probably Google. Good work Piers!
